export enum ProviderCapability {
  AIRTIME = 'AIRTIME',
  DATA = 'DATA',
  ELECTRICITY = 'ELECTRICITY',
  CABLE = 'CABLE',
  JAMB = 'JAMB',
  WAEC = 'WAEC',

  NIN_VERIFICATION = 'NIN_VERIFICATION',
  BVN_VERIFICATION = 'BVN_VERIFICATION',

  ACCOUNT_CREATION = 'ACCOUNT_CREATION',
  TRANSFER = 'TRANSFER',
}
